<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE timeTable [
	<!ELEMENT timeTable (lesson+, offices)>
	<!ELEMENT lesson (date, time)>
	<!ATTLIST lesson no CDATA #REQUIRED>
	<!ELEMENT date (#PCDATA)>
	<!ELEMENT time (#PCDATA)>
	<!ELEMENT offices (office+)>
	<!ELEMENT office (name, address)>
	<!ATTLIST office code CDATA #IMPLIED>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT address (#PCDATA)>
]>
<timeTable>
	<lesson no="1">
		<date>2015-07-06</date>
		<time>14:55:40</time>
	</lesson>
	<lesson no="2">
		<date>2015-07-10</date>
		<time>14:25:00</time>
	</lesson>
	<lesson no="3">
		<date>2015-07-10</date>
		<time>14:25:00</time>
	</lesson>
	<offices>
		<office code="БЛ">
			<name>Комплекс 10</name>
			<address>Ключевского, 5</address>
		</office>
		<office code="КЕ">
			<name>Комплекс 45</name>
			<address>Мостовая, 44</address>
		</office>
	</offices>
</timeTable>