=== almazka/miniprojects/xml/xml-example-schema-pro.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:complexType name="lessonsType">
	<xs:sequence>
		<xs:element name="date" type="xs:date" />
		<xs:element name="time" type="xs:time" />
	</xs:sequence>
<xs:attribute name="no" type="xs:ID" use="required" />
</xs:complexType>
<xs:complexType name="officesType">
	<xs:sequence>
		<xs:element name="name" type="xs:string" />
		<xs:element name="address" type="xs:string" />
	</xs:sequence>
<xs:attribute name="code" type="xs:ID" use="required" />
</xs:complexType>	
<xs:complexType name="notesType">
	<xs:sequence>
		<xs:element name="lesson" type="lessonsType" minOccurs="0" maxOccurs="unbounded" />
		<xs:element name="offices" type="officesType" minOccurs="0" maxOccurs="unbounded" />
	</xs:sequence>
</xs:complexType>	

	<xs:element name="timeTable" type="notesType" />
</xs:schema>

=== almazka/miniprojects/xml/xml-example-schema-pro.xml
<?xml version="1.0" encoding="utf-8" ?>
<timeTable
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="xml-example-schema-pro.xsd">

	<lesson no="1">
		<date>2015-07-06</date>
		<time>14:55:40</time>
	</lesson>
	<lesson no="2">
		<date>2015-07-10</date>
		<time>14:25:00</time>
	</lesson>
	<lesson no="3">
		<date>2015-07-10</date>
		<time>14:25:00</time>
	</lesson>
	
	<offices>
		<office code="БЛ">
			<name>Комплекс 10</name>
			<address>Ключевского, 5</address>
		</office>
		<office code="КЕ">
			<name>Комплекс 45</name>
			<address>Мостовая, 44</address>
		</office>
	</offices>
</timeTable>
